batch_size: 2000
epochs: 400
eval_every_n_epochs: 5
smilesmodel_finetune: True
smilesmodel_finetune_path: ".../nist_w2v/pretrained_gin/checkpoints/model.pth"
fine_tune_from: " "
log_every_n_steps: 2
learning_rate: 5e-05
weight_decay: 0.0001
fp16_precision: True
truncation: True

model_config:
  num_layer: 5
  emb_dim: 300
  feat_dim: 512
  drop_ratio: 0.3
  pool : mean
  channels: 32
  input_channels: 300
  output_channels: 256
  embed_dim: 256
  
dataset:
  s: 1
  num_workers: 4
  valid_size: 0.2
  ms2_file: ""
  smi_file: ""
  spec2vec_model_file: ".../nist_w2v/references.model"

loss:
  temperature: 0.1
  use_cosine_similarity: True
  alpha_weight: 0.75
